name: Simple Website CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Stage
        run: |
          echo "✅ Build complete. HTML file exists: $(ls index.html)"

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Website Repo
        uses: actions/checkout@v3

      - name: Install Python + Pytest
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python Dependencies
        run: |
          pip install pytest selenium pytest-html

      - name: Checkout Automation Test Repo
        uses: actions/checkout@v3
        with:
          repository: shubhamsfit/Automation-Testing
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          path: automation-tests

      - name: Run Automation Tests
        run: |
          cd automation-tests
          pytest

      - name: Upload HTML report artifact
        uses: actions/upload-artifact@v4
        with:
          name: selenium-test-report
          path: reports/report.html

      - name: Send test report via email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtppro.zoho.in
          server_port: 465
          secure: true
          username: ${{ secrets.EMAIL_USERNAME }}    # e.g. reports@yourdomain.com
          password: ${{ secrets.EMAIL_PASSWORD }}    # App-specific password
          subject: Selenium Test Report
          to: shubham.kohli@simplefixit.com, shubhamkohli2002@gmail.com
          from: ${{ secrets.EMAIL_USERNAME }}
          body: |
            Hi,

            Please find the attached Selenium test report from the scheduled run.

            Regards,  
            GitHub Actions
          attachments: reports/report.html

  deploy:
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: write  # Needed to push back to the repo
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: true  # Uses GITHUB_TOKEN for push

      - name: Prepare Files (if needed)
        run: |
          echo "✅ Ready to deploy - contents:"
          ls -la

      - name: Commit & Push Build Output
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add index.html
          git commit -m "Deploy updated site [skip ci]" || echo "No changes to commit"
          git push origin main
