name: Simple Website CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Stage
        run: |
          echo "✅ Build complete. HTML file exists: $(ls index.html)"

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Website Repo
        uses: actions/checkout@v3

      - name: Install Python + Pytest
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python Dependencies
        run: |
          pip install pytest selenium pytest-html

      - name: Checkout Automation Test Repo
        uses: actions/checkout@v3
        with:
          repository: shubhamsfit/Automation-Testing
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          path: automation-tests

      - name: Run Automation Tests and Generate HTML Report
        run: |
          cd automation-tests
          pytest --html=report.html --self-contained-html

      - name: Move report to reports directory
        run: |
          mkdir -p automation-tests/reports
          mv automation-tests/report.html automation-tests/reports/index.html

      - name: Deploy report.html to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: automation-tests/reports
          publish_branch: gh-pages
          keep_files: false

      - name: Send Test Report URL via Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtppro.zoho.in
          server_port: 465
          secure: true
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Dentana Automation Testing Report
          to: shubhamkohli2002@gmail.com
          cc: shubham.kohli@simplefixit.com
          from: ${{ secrets.EMAIL_USERNAME }}
          body: |
            Hi,

            The latest Dentana Automation Testing Report is available online at:

            https://shubhamsfit.github.io/Project-Website-One/reports/

            Please review it at your convenience & let me know in case of any query.

            Best Regards,  
            Shubham Kohli  
            Quality Analyst

  deploy:
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Prepare Files (if needed)
        run: |
          echo "✅ Ready to deploy - contents:"
          ls -la

      - name: Commit & Push Build Output
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add index.html
          git commit -m "Deploy updated site [skip ci]" || echo "No changes to commit"
          git push origin main
