name: Simple Website CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Stage
        run: |
          echo "✅ Build complete. HTML file exists: $(ls index.html)"

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Website Repo
        uses: actions/checkout@v3

      - name: Install Python + Pytest
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python Dependencies
        run: |
          pip install pytest selenium pytest-html

      - name: Checkout Automation Test Repo
        uses: actions/checkout@v3
        with:
          repository: shubhamsfit/Automation-Testing
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          path: automation-tests

      - name: Run Automation Tests and Generate HTML Report
        run: |
          cd automation-tests
          pytest --html=report.html --self-contained-html

      - name: Deploy report.html to GitHub Pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          publish_dir: automation-tests # Contains report.html
          publish_branch: gh-pages
          keep_files: false

      - name: Send Test Report URL via Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtppro.zoho.in
          server_port: 465
          secure: true
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Dentana Automation Testing Report
          to: shubhamkohli2002@gmail.com
          cc: shubham.kohli@simplefixit.com
          from: ${{ secrets.EMAIL_USERNAME }}
          body: |
            Hi,

            The latest Dentana Automation Testing Report is available online at:

            https://shubhamsfit.github.io/Project-Website-One/report.html

            Please review it at your convenience.

            Best Regards,  
            Shubham Kohli
            Quality Analyst
