name: Simple Website CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Stage
        run: |
          echo "✅ Build complete. HTML file exists: $(ls index.html)"

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Website Repo
        uses: actions/checkout@v3

      - name: Install Python + Pytest
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Clone Automation Test Repo
        run: |
          git clone https://github.com/shubhamsfit/Automation-Testing.git automation-tests
          ls automation-tests

      - name: Run Automation Tests
        run: |
          cd automation-tests
          pytest

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
